# Stage 2 integrity invariants

Complete package `TK-20261004-S2-systems-engineer-IMPLEMENT-1`, six parts and END marker, acknowledged in room message `4501939a-e948-482a-9549-f61aa538f2e6` before work. The accepted Stage 1 revision is `2a4b0408a3453bc87d86bca3d0ec571f479e03ca`. The manifest/verdict hashes and all five source files were verified before one complete folder copy. `stage-2-source-copy.json` records exact hashes; copy handoff `2563f220-6885-4eb4-8b76-ef7c940d832f` released Interface-owned paths. Stage 1 is frozen.

- The existing Engine RLock remains the complete transaction/read boundary. Shared state and immutable receipt snapshots remain in the same single-container engine; transport/browser behavior is Interface-owned.
- A seating selection is one table or a declared unordered pair. Requested pair order is canonicalized to the declaration's order, using the first matching declaration. No transitive or three-member combination exists. The combined capacity is the exact sum of member capacities.
- Availability enumerates eligible unoccupied singles in fixture order, then every eligible declared pair in combinable order. Existing available_table_ids contains singles only. Overlap is an intersecting member set and a half-open absolute time interval in the same restaurant.
- Create, amendment and batch moves validate all member selections/capacity/time before atomic occupancy mutation. Pair/single transitions remove obsolete seating fields. Failed operations cannot consume keys or release any old member. Cancel releases all confirmed members; cancelled seeded pairs have no occupancy.
- New responses contain table_ids and include table_id only for singles. Legacy Stage 1 record import adds the current seating representation while preserving account, token, identity, status, timestamp and original wall values. Successful original Stage 1 receipt JSON stays unchanged, even when it lacks the newly added table_ids field; it is never regenerated from the current record.
- Create/batch idempotency continues to compare the original parsed JSON request, including input ordering and ignored fields. Reverse member order alone is a different create retry body with a used key, even though both selections canonicalize identically for occupancy. Failed keys remain reusable.
- Import validates records and receipts using canonical member sets without imposing the request-only prohibition against redundant singleton response fields. New Stage 2 exports round-trip exactly; genuine Stage 1 exports remain accepted independent of source process. Invalid replacement is atomic.
- Legacy receipt snapshots without table_ids identify the Stage 1 request interpretation: their original bodies may contain ignored table_ids values. Import ignores that newly recognized field only while validating those old successful snapshots, preserves the full parsed body, and replays the original receipt. A new request/key follows Stage 2's current rules. Genuine source-service tests cover old create and batch bodies with this formerly ignored field.
- All accepted validation, hashing, current-start cutoff, integer/calendar boundary handling, exact duration, DST first-occurrence and recorded historic RFC3339 interpretation remain inherited. No Stage 3/4 fields or endpoints are implemented.

Source inputs: full package task, inherited/new specs, acceptance brief and timestamp decision; current immutable room plan; accepted manifest and candidate-4 verdict; own frozen Stage 1 core and earlier authored diagnostics. No shipped tests, broad verifier probe/oracle implementation, external domain product docs/code, abandoned result or memory files are used. New builder diagnostics derive from these invariants and the full specifications. Runtime tools are workspace Python, Git, Docker and configured Jam CLI. Harness Codex; configured gpt-6.1-sol; actual model override/effort/usage/spend unknown.
